### ISSUE TITLE
Show Chapter Benefits

### ISSUE THREAD

**Issue by malkam03** [TEComputerIEEE/IEEE-TEC-Bot#2]
Return the IEEE Chapter Benefits to the user when the command is evoked.

**Comment by malkam03** [comment]
The information methods need to be in the information module and not in the main. See the last version of the main 8abe876 for further details. The keyboard and the file i/o shouldn't be together as in 531c068.

**Comment by malkam03** [comment]
@Gutima15  remember to use the  [mockups.pdf](https://github.com/TEComputerIEEE/IEEE-TEC-Bot/blob/master/Mockups.pdf)  to format the output correctly.

**Comment by Gutima15** [comment]
Thx Malcom, ahorita lo que estoy haciendo es descubrir cómo funciona el
bot, logré enviar mjs, me falta agregarle la info y que no se caiga 🤣
Espero lograr salir con eso pronto. Si no me equivoco el primer mjs que me
envió es a cuestión de ubicación en el Github y lo segundo aún no lo he
visto, no me abrió en el cel pero genial, gracias. Yo lo haré así como me
indica.
